### ISSUE TITLE
Deleting an Ilios Sync instance does not un-enroll user

### ISSUE THREAD

**Issue by ctam** [ilios/moodle-enrol-ilios#11]
After I deleted an Ilios Sync instance in a course, I could still find those users with role assigned under 'Other users'.  They do not show up under 'Enrolled users' list, though, which is correct.

Technical note:  These users need to be removed from both `user_enrolments` and `role_assignments` tables, depending on `Unenrolaction` value.

**Comment by stopfstedt** [comment]
can't reproduce.

i poked around in that code a bit today, and `enrol_plugin::delete_instance()` deletes all relevant records from the `user_enrolments` and `role_assignments` tables, among others.

@ctam possible that these remaining users were enrolled manually _and_ via the ilios sync?

**Comment by stopfstedt** [comment]
another idea - perhaps those users were assigned as course participants in addition to being enrolled?

**Comment by stopfstedt** [comment]
closed due to inactivity.
